---
- name: Install Docker on all nodes
  hosts: all
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Enable & start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started
