version: "3.8"

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    networks:
      - Infra_stack
    volumes:
      - registry_data:/var/lib/registry
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      placement:
        constraints: [node.hostname == vm01]

volumes:
  registry_data:

networks:
  Infra_stack:
    external: true
