version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9090:9090"
      - "8080:8090"
    networks:
      - Infra_stack
    deploy:
      placement:
        constraints: [node.hostname == vm01]

networks:
  Infra_stack:
    external: true
