version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - cicd_stack
    deploy:
      placement:
        constraints: [node.hostname == vm02]
    restart: always
    
networks:
  cicd_stack:
    external: true
