version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - Infra_stack
    deploy:
      placement:
        constraints: [node.hostname == vm02]
    restart: always
    
networks:
  Infra_stack:
    external: true
