- name: Triển khai ứng dụng Nginx
  hosts: web
  become: true
  tasks:
    - name: creating dir /home/ubuntu/sourcecode
      file:
        path: /home/ubuntu/sourcecode
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy file index.html
      copy:
        src: index.html
        dest: /home/ubuntu/sourcecode/
    
    
