version: '3.8'

services:
  jenkins:
    image: custom/img-jenk-ans-ter:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    user: root
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - Infra_stack
    deploy:
      placement:
        constraints:
          - node.hostname == vm01
      restart_policy:
        condition: any

volumes:
  jenkins_data:

networks:
  Infra_stack:
    external: true