STACK_NAME: Infra_stack
NETWORK_NAME: network_infra_stack
HOST_GRAFANA: worker2
HOST_JENKINS: leader1
HOST_PROMETHEUS: leader1
HOST_REGISTRY: leader1
IP_LEADER1: 192.168.11.11
IP_WORKER1: 192.168.11.12
IP_WORKER2: 192.168.11.13